// ──────────────────────────────────────────────────────────────────────────────
// lib/agents/scorecard/critic-discriminator.ts
// The Critic Churn Discriminator — the factory's FIRST slow-loop (adaptation)
// sensor. Sibling of computeScorecard (the reflex sensor). Read-only.
//
// The reflex contour asks "did this episode ship?". The adaptation contour asks
// "did the churn we spent TEACH us something that should change the factory so it
// doesn't recur?". This deriver answers, per critic:
//
//   Was the churn the CRITIC being too hard/noisy (false-rejects), or the
//   PRODUCER being weak (work that legitimately failed)?  — and proposes the fix.
//
// WHY it exists (E28 forensic, 2026-07-14): "CREAD ran 2.45×/shot" looked like
// critic churn but was a MEASUREMENT ARTIFACT — 54 runs, only 3 REVISE (94.5%
// first-pass PASS); the "churn" was idempotent re-checks of plans the Director
// regenerated by hand (creative revision), not the critic bouncing work. Naive
// runs/shot mis-diagnoses every episode with re-trigger waves. So this sensor
// measures THREE distinct axes, never one:
//   1. Critic churn      = REVISE bounces per artifact VERSION (not runs/shot).
//   2. Producer rework   = Director-rejected first-pass creative assets / shot.
//   3. Rework regens     = superseded (INVALIDATED) asset versions = paid rework.
//
// Discriminator method (per critic, per bounced artifact lineage):
//   • REVISE→PASS on the SAME artifact id, or ~identical content → critic NOISY.
//   • REVISE→PASS only after SUBSTANTIVE producer change            → producer weak-but-fixable.
//   • REVISE→REVISE on the SAME rubric point (R0x) across a change  → producer CAPABILITY GAP.
//   • bounces on VARIED/contradictory points run-to-run             → critic INCONSISTENT.
//
// Pure read: assets (REV-* verdict rows + reviewed-artifact content) + the
// activity_events already loaded by computeScorecard. Reuses actorKind. No writes
// — the escalation side-effect lives in refreshScorecard (escalate-zone → Inbox).
// ──────────────────────────────────────────────────────────────────────────────

import type { SupabaseClient } from '@supabase/supabase-js';

import type { Database } from '@/lib/supabase/types.gen';
import { actorKind } from '@/lib/api/agent-names';

type Sb = SupabaseClient<Database>;

/** Fraction of char change below which a REVISE→PASS flip is treated as the
 *  critic flipping on ~identical producer work (noise), not a real fix. */
const NOISE_DELTA_FRACTION = 0.1;

export type CriticVerdictClass =
  | 'healthy' // 0 REVISE — critic passed the producer's work first look
  | 'producer_gap' // same rubric point survives a producer rewrite = capability gap
  | 'producer_weak_fixable' // bounced, producer substantively fixed, passed — loop working
  | 'critic_too_hard' // REVISE→PASS on ~identical work = false-reject / noisy
  | 'critic_inconsistent'; // varied/contradictory points run-to-run

export type CalibrationZone = 'auto_safe' | 'escalate' | 'none';

export interface CriticProposal {
  critic: string;
  zone: CalibrationZone;
  action: string;
  target: string;
  rationale: string;
}

export interface PerCriticVerdict {
  critic: string; // agent_id, e.g. EXEC-CREAD
  reviewKinds: string[];
  totalRuns: number;
  reviseCount: number;
  verdict: CriticVerdictClass;
  repeatedPoints: string[]; // rubric points (R0x) repeated across bounces
  flaggedPoints: string[]; // all rubric points ever flagged
  evidence: string;
}

export interface CriticDiscriminatorResult {
  perCritic: PerCriticVerdict[];
  // Axis 1
  trueCriticChurn: number; // total REVISE across all critics (the honest churn)
  // Axis 2 — producer first-pass quality
  producerRejects: { human: number; aiEp: number; total: number };
  rejectedShots: number;
  producerFirstPassRejectRate: number | null; // rejectedShots / shotCount
  // Axis 3 — paid rework
  reworkRegens: number; // superseded (INVALIDATED) asset versions
  headline: string;
  proposals: CriticProposal[];
}

interface RevRow {
  agent_id: string;
  file_type: string;
  version: number;
  status: string;
  created_at: string;
  metadata: {
    verdict?: string;
    review_kind?: string;
    phase?: string;
    shot_id?: string;
    plan_asset_id?: string;
    failed_checks?: unknown;
  } | null;
}

type ActRow = { event_type: string; actor: string | null; metadata: unknown };

/** Normalise a failed_checks payload to bare rubric codes (R01…R0N / any TOKEN). */
function rubricPoints(failed: unknown): string[] {
  if (!Array.isArray(failed)) return [];
  const out: string[] = [];
  for (const f of failed) {
    if (typeof f === 'string') {
      const m = f.match(/R\d{1,2}/i);
      if (m) out.push(m[0].toUpperCase());
    } else if (f && typeof f === 'object') {
      const c = (f as { check?: unknown; id?: unknown }).check ?? (f as { id?: unknown }).id;
      if (typeof c === 'string') {
        const m = c.match(/R\d{1,2}/i);
        out.push(m ? m[0].toUpperCase() : c);
      }
    }
  }
  return out;
}

const isRevise = (v: string | undefined): boolean => v === 'REVISE';
const isPassish = (v: string | undefined): boolean =>
  v === 'PASS' || v === 'PASS_WITH_UNCERTAINTY';

/** Bare SH token, else null. Mirrors compute-scorecard.shotToken. */
function shotToken(v: unknown): string | null {
  if (typeof v !== 'string') return null;
  const m = v.match(/SH\d+/i);
  return m ? m[0].toUpperCase() : null;
}

/** Classify one critic's ordered verdict rows into a verdict + evidence.
 *  `deltas` maps a REVISE row index → normalised content delta of the fix that
 *  followed (null when unknown / same artifact id). */
function classifyCritic(
  critic: string,
  rows: RevRow[],
  deltas: Map<number, number | null>,
): PerCriticVerdict {
  const reviewKinds = [
    ...new Set(rows.map((r) => r.metadata?.review_kind ?? r.metadata?.phase ?? 'default')),
  ];
  const reviseRows = rows.filter((r) => isRevise(r.metadata?.verdict));
  const reviseCount = reviseRows.length;

  // rubric-point frequency across bounces
  const pointFreq: Record<string, number> = {};
  for (const r of reviseRows) {
    for (const p of new Set(rubricPoints(r.metadata?.failed_checks))) {
      pointFreq[p] = (pointFreq[p] ?? 0) + 1;
    }
  }
  const flaggedPoints = Object.keys(pointFreq).sort();
  const repeatedPoints = flaggedPoints.filter((p) => pointFreq[p] >= 2);

  // transition character: how were the REVISE→PASS flips resolved?
  let noiseFlips = 0; // ~identical work → critic too hard
  let substantiveFlips = 0; // real producer fix
  for (const [idx, delta] of deltas) {
    if (delta === null) continue;
    if (delta < NOISE_DELTA_FRACTION) noiseFlips += 1;
    else substantiveFlips += 1;
    void idx;
  }

  let verdict: CriticVerdictClass;
  let evidence: string;
  if (reviseCount === 0) {
    verdict = 'healthy';
    evidence = `${rows.length} runs, 0 REVISE — passed first look`;
  } else if (repeatedPoints.length > 0) {
    verdict = 'producer_gap';
    evidence = `rubric ${repeatedPoints.join(',')} survived a producer rewrite (${reviseCount} REVISE)`;
  } else if (noiseFlips > substantiveFlips && noiseFlips > 0) {
    verdict = 'critic_too_hard';
    evidence = `${noiseFlips} REVISE→PASS flip(s) on ~identical work — likely false-reject`;
  } else if (substantiveFlips > 0) {
    verdict = 'producer_weak_fixable';
    evidence = `${substantiveFlips} bounce(s) resolved by substantive producer fix — loop working`;
  } else if (flaggedPoints.length >= 3) {
    verdict = 'critic_inconsistent';
    evidence = `${reviseCount} REVISE across varied points ${flaggedPoints.join(',')} — no stable target`;
  } else {
    verdict = 'producer_weak_fixable';
    evidence = `${reviseCount} REVISE, ${flaggedPoints.join(',') || 'no rubric codes'}`;
  }

  return {
    critic,
    reviewKinds,
    totalRuns: rows.length,
    reviseCount,
    verdict,
    repeatedPoints,
    flaggedPoints,
    evidence,
  };
}

/** Map a per-critic verdict to a calibration proposal + its reversibility zone.
 *  auto_safe = reversible (rubric wording / prompt / tier) — applied without a
 *  Director touch. escalate = creative/training change (producer skill) —
 *  irreversible-ish, needs the Director. none = nothing to change. */
export function proposeCalibration(v: PerCriticVerdict): CriticProposal {
  switch (v.verdict) {
    case 'healthy':
    case 'producer_weak_fixable':
      return {
        critic: v.critic,
        zone: 'none',
        action: 'no calibration — critic and producer loop are healthy',
        target: '—',
        rationale: v.evidence,
      };
    case 'critic_too_hard':
      return {
        critic: v.critic,
        zone: 'auto_safe',
        action: `soften ${v.critic} rubric threshold/wording on ${v.flaggedPoints.join(',') || 'flagged points'}`,
        target: 'critic rubric wording (reversible)',
        rationale: v.evidence,
      };
    case 'critic_inconsistent':
      return {
        critic: v.critic,
        zone: 'auto_safe',
        action: `stabilise ${v.critic} — tighten prompt determinism / lower temperature`,
        target: 'critic prompt (reversible)',
        rationale: v.evidence,
      };
    case 'producer_gap':
      return {
        critic: v.critic,
        zone: 'escalate',
        action: `train the producer on ${v.repeatedPoints.join(',')} — the point survives a rewrite`,
        target: 'producer skill / prompt (creative change)',
        rationale: v.evidence,
      };
  }
}

/**
 * Compute the critic discriminator for one episode. Pure read.
 * `acts` + `shotCount` are threaded from computeScorecard to avoid a second big
 * paged read; when omitted the function still works (acts→[] degrades axis 2).
 */
export async function computeCriticDiscriminator(
  supabase: Sb,
  episodeId: string,
  opts: { acts?: ActRow[]; shotCount?: number },
): Promise<CriticDiscriminatorResult> {
  const shotCount = opts.shotCount ?? 0;

  // 1. All critic verdict rows (REV-* with a verdict), newest-last. Exclude the
  //    scorecard render itself (REV-scorecard is not a critic).
  const { data: revData, error } = await supabase
    .from('assets')
    .select('agent_id, file_type, version, status, created_at, metadata')
    .eq('episode_id', episodeId)
    .like('file_type', 'REV-%')
    .neq('file_type', 'REV-scorecard')
    .order('created_at', { ascending: true });
  if (error) throw new Error(`critic-discriminator REV fetch failed: ${error.message}`);
  const revs = (revData ?? []).filter(
    (r) => typeof (r as RevRow).metadata?.verdict === 'string',
  ) as RevRow[];

  // 2. Producer-fix deltas — only for REVISE→PASS transitions, keyed per critic
  //    per shot lineage. Fetch reviewed-artifact content lazily (cheap: few
  //    REVISE rows/episode). plan_asset_id identical across the flip ⇒ delta 0
  //    (critic flipped on the SAME artifact). Different ⇒ char-normalised delta.
  const byCriticShot = new Map<string, RevRow[]>();
  for (const r of revs) {
    const key = `${r.agent_id}::${r.metadata?.shot_id ?? r.file_type}`;
    (byCriticShot.get(key) ?? byCriticShot.set(key, []).get(key)!).push(r);
  }
  const planIdsToFetch = new Set<string>();
  const flips: Array<{ critic: string; reviseIdx: number; prevPlan?: string; nextPlan?: string }> = [];
  for (const rows of byCriticShot.values()) {
    for (let i = 0; i < rows.length - 1; i++) {
      if (isRevise(rows[i].metadata?.verdict) && isPassish(rows[i + 1].metadata?.verdict)) {
        const prevPlan = rows[i].metadata?.plan_asset_id;
        const nextPlan = rows[i + 1].metadata?.plan_asset_id;
        if (prevPlan) planIdsToFetch.add(prevPlan);
        if (nextPlan) planIdsToFetch.add(nextPlan);
        flips.push({ critic: rows[i].agent_id, reviseIdx: i, prevPlan, nextPlan });
      }
    }
  }
  const planContent = new Map<string, string>();
  if (planIdsToFetch.size > 0) {
    const { data: plans } = await supabase
      .from('assets')
      .select('id, content')
      .in('id', [...planIdsToFetch]);
    for (const p of plans ?? []) planContent.set((p as { id: string }).id, (p as { content?: string }).content ?? '');
  }
  // per-critic REVISE-index → delta
  const deltaByCritic = new Map<string, Map<number, number | null>>();
  for (const f of flips) {
    const m = deltaByCritic.get(f.critic) ?? deltaByCritic.set(f.critic, new Map()).get(f.critic)!;
    let delta: number | null = null;
    if (f.prevPlan && f.nextPlan) {
      if (f.prevPlan === f.nextPlan) {
        delta = 0; // critic flipped on the SAME artifact — pure noise
      } else {
        const a = planContent.get(f.prevPlan) ?? '';
        const b = planContent.get(f.nextPlan) ?? '';
        const denom = Math.max(a.length, b.length, 1);
        delta = Math.abs(b.length - a.length) / denom; // cheap length-normalised proxy
      }
    }
    m.set(f.reviseIdx, delta);
  }

  // 3. Per-critic classification.
  const byCritic = new Map<string, RevRow[]>();
  for (const r of revs) {
    (byCritic.get(r.agent_id) ?? byCritic.set(r.agent_id, []).get(r.agent_id)!).push(r);
  }
  const perCritic: PerCriticVerdict[] = [];
  for (const [critic, rows] of byCritic) {
    perCritic.push(classifyCritic(critic, rows, deltaByCritic.get(critic) ?? new Map()));
  }
  perCritic.sort((a, b) => b.reviseCount - a.reviseCount || a.critic.localeCompare(b.critic));
  const trueCriticChurn = perCritic.reduce((s, c) => s + c.reviseCount, 0);

  // 4. Axis 2 — producer first-pass reject rate (Director/AI rejected a creative
  //    first pass, forcing a paid regeneration). Creative = non-REV asset.
  const acts = opts.acts ?? [];
  let rejHuman = 0;
  let rejAi = 0;
  const rejShots = new Set<string>();
  for (const a of acts) {
    if (a.event_type !== 'approval_revision' && a.event_type !== 'approval_rejected') continue;
    const ft = (a.metadata as { file_type?: unknown } | null)?.file_type;
    if (typeof ft === 'string' && ft.startsWith('REV-')) continue; // mechanical, not producer work
    const kind = actorKind(a.actor);
    if (kind === 'director') rejHuman += 1;
    else if (kind === 'ai-director') rejAi += 1;
    else continue;
    const tok = shotToken(typeof ft === 'string' ? ft : null);
    if (tok) rejShots.add(tok);
  }
  const producerRejects = { human: rejHuman, aiEp: rejAi, total: rejHuman + rejAi };
  const rejectedShots = rejShots.size;
  const producerFirstPassRejectRate =
    shotCount > 0 ? +(rejectedShots / shotCount).toFixed(3) : null;

  // 5. Axis 3 — paid rework: superseded creative asset versions (INVALIDATED /
  //    version > 1 on the same lineage). Read the version ledger for creative
  //    plan assets (SPC-ref_plan / SPC-shot_plan) — the E28 regen story lived here.
  const { data: planVers } = await supabase
    .from('assets')
    .select('file_type, version, status')
    .eq('episode_id', episodeId)
    .or('file_type.ilike.SPC-ref_plan%,file_type.ilike.SPC-shot_plan%');
  const reworkRegens = (planVers ?? []).filter(
    (p) => (p as { version?: number }).version && (p as { version: number }).version > 1,
  ).length;

  // 6. Proposals + headline.
  const proposals = perCritic.map(proposeCalibration).filter((p) => p.zone !== 'none');
  const churnDom =
    perCritic.find((c) => c.verdict === 'producer_gap') ??
    perCritic.find((c) => c.verdict === 'critic_too_hard') ??
    perCritic.find((c) => c.verdict === 'critic_inconsistent');
  const rejPct =
    producerFirstPassRejectRate !== null ? `${Math.round(producerFirstPassRejectRate * 100)}%` : 'n/a';
  const headline =
    trueCriticChurn === 0 && !churnDom
      ? `Critic healthy (0 REVISE). Real cost = ${rejPct} first-pass reject rate (${rejectedShots}/${shotCount} shots), ${reworkRegens} paid regens.`
      : `${trueCriticChurn} true REVISE · dominant: ${churnDom?.critic ?? 'n/a'} ${churnDom?.verdict ?? ''}. First-pass reject ${rejPct}, ${reworkRegens} regens.`;

  return {
    perCritic,
    trueCriticChurn,
    producerRejects,
    rejectedShots,
    producerFirstPassRejectRate,
    reworkRegens,
    headline,
    proposals,
  };
}
