// ──────────────────────────────────────────────────────────────────────────────
// lib/providers/video-gen-multi.ts
// Provider-agnostic abstraction for video generation (Universal Video Editor
// Surface, Phase 1 of purrfect-stirring-hollerith plan).
//
// Why an abstraction layer:
//   - VGEN is the final visible output. Director must be able to switch
//     providers per shot (Veo 3 today, Kling/Sora/fal.ai tomorrow) without UI
//     or runner rewrites.
//   - Providers expose different per-stage controls. Universal Core knobs
//     (aspect/quality/duration/prompt/reference) live on this interface;
//     provider-specific knobs ride on the manifest in Phase 2.
//
// Phase 1 ships ONE concrete provider (Veo 3 via Gemini, generated by
// `veo-gemini.ts`). The wrapper below normalises the call surface so the
// runner doesn't import veo-gemini directly when extra providers land.
// ──────────────────────────────────────────────────────────────────────────────

import {
  generateVideoVeoGemini,
  type VeoAspectRatio,
  type VeoQualityTier,
  type VeoGeminiResult,
} from './veo-gemini';
import {
  generateVideoFalSeedance,
  type FalSeedanceResult,
} from './fal-seedance';
import {
  generateVideoFalWan,
  type FalWanResult,
} from './fal-wan';

// ── Universal Core types ─────────────────────────────────────────────────────

// Aspect/resolution sets are super-sets of any single provider's capability;
// adapters reject or downgrade values they don't support.
export type MultiVideoAspectRatio = '16:9' | '9:16' | '1:1' | '21:9' | '4:3' | '3:4' | 'auto';
export type MultiVideoQualityTier = VeoQualityTier;
export type MultiVideoResolution = '480p' | '720p' | '1080p';

export interface MultiVideoGenInput {
  /** Composed prompt (already merged with shot details + episode title). */
  prompt: string;
  /** Universal Core: 16:9 (YouTube), 9:16 (Reels/Shorts), 1:1 (square), or
   * provider extensions (21:9 / 4:3 / 3:4 / auto inferred from reference). */
  aspectRatio?: MultiVideoAspectRatio;
  /** Universal Core: 'fast' (cheap) vs 'standard' (higher quality). */
  quality?: MultiVideoQualityTier;
  /** Universal Core: 4-15 second clips. Providers clamp to their own range. */
  durationSeconds?: number;
  /** Universal Core: optional img2vid reference frame (start). */
  referenceImageBase64?: string;
  referenceImageMime?: 'image/png' | 'image/jpeg';
  /** Sprint β 2026-05-14: 480p / 720p / 1080p — provider may downgrade. */
  resolution?: MultiVideoResolution;
  /** Sprint β 2026-05-14: reproducibility seed (Seedance only currently). */
  seed?: number;
  /** Sprint β 2026-05-14: optional end-frame for start-to-end transition.
   * Seedance only currently; Veo ignores. */
  endImageBase64?: string;
  endImageMime?: 'image/png' | 'image/jpeg';
}

export interface MultiVideoGenResult {
  status: 'success';
  /** Stable provider id. e.g. 'veo-3-img2vid' or 'veo-3'. */
  provider: string;
  format: 'MP4';
  width: number;
  height: number;
  duration_seconds: number;
  size_bytes: number;
  /** Base64-encoded MP4 bytes. */
  mp4_b64: string;
  cost_usd: number;
  /**
   * Underlying model id (e.g. `veo-3.1-fast-generate-preview`). Optional
   * because non-Veo providers (Kling/Sora) may use different ids; runner
   * persists when present.
   */
  model_id?: string;
  /** Provider-side operation/job id for cross-reference in vendor logs. */
  operation_name?: string;
}

export interface MultiVideoGenCapabilities {
  supports_aspects: ReadonlyArray<MultiVideoAspectRatio>;
  supports_qualities: ReadonlyArray<MultiVideoQualityTier>;
  supports_reference_image: boolean;
  /**
   * I5 (gate-hardening 2026-06-04): provider is img2vid and CANNOT run
   * imageless. "accepts a reference" (supports_reference_image) is not the same
   * as "requires one" — an img2vid model run without a frame silently degrades
   * to text-to-video and drifts identity (Sandy → squirrel) or 422s. When true,
   * the runner throws BEFORE the paid call if no reference image resolved.
   */
  requires_reference_image: boolean;
  /** Min/max clip duration in seconds. */
  min_duration_s: number;
  max_duration_s: number;
  /** Sprint β 2026-05-14 — capability manifest extension. */
  supports_resolutions: ReadonlyArray<MultiVideoResolution>;
  supports_seed: boolean;
  supports_end_image: boolean;
  /** Soft prompt cap; UI uses to warn before submit. */
  max_prompt_chars?: number;
}

export interface MultiVideoGenProvider {
  /** Stable id used in `app_config` and asset metadata. */
  id: string;
  capabilities: MultiVideoGenCapabilities;
  generate(input: MultiVideoGenInput): Promise<MultiVideoGenResult>;
}

export class MultiVideoGenError extends Error {
  constructor(
    message: string,
    public readonly providerId: string,
    public readonly cause?: unknown,
  ) {
    super(message);
    this.name = 'MultiVideoGenError';
  }
}

// ── Veo 3 wrapper ────────────────────────────────────────────────────────────

const VEO_CAPABILITIES: MultiVideoGenCapabilities = {
  supports_aspects: ['16:9', '9:16', '1:1'],
  supports_qualities: ['fast', 'standard'],
  supports_reference_image: true,
  requires_reference_image: true,
  min_duration_s: 4,
  max_duration_s: 8,
  // Veo 3 renders at fixed model resolution; do not expose a chooser.
  supports_resolutions: [],
  supports_seed: false,
  supports_end_image: false,
  max_prompt_chars: 2000,
};

function veoResultToMulti(r: VeoGeminiResult): MultiVideoGenResult {
  return {
    status: 'success',
    provider: r.provider,
    format: r.format,
    width: r.width,
    height: r.height,
    duration_seconds: r.duration_seconds,
    size_bytes: r.size_bytes,
    mp4_b64: r.mp4_b64,
    cost_usd: r.cost_usd,
    model_id: r.model_id,
    operation_name: r.operation_name,
  };
}

export const veo3Provider: MultiVideoGenProvider = {
  id: 'veo-3-img2vid',
  capabilities: VEO_CAPABILITIES,
  async generate(input: MultiVideoGenInput): Promise<MultiVideoGenResult> {
    try {
      // Veo accepts only 16:9 / 9:16 / 1:1; downgrade any wider aspect to 16:9.
      const veoAspect: VeoAspectRatio | undefined =
        input.aspectRatio === '16:9' ||
        input.aspectRatio === '9:16' ||
        input.aspectRatio === '1:1'
          ? input.aspectRatio
          : input.aspectRatio
            ? '16:9'
            : undefined;
      const r = await generateVideoVeoGemini({
        prompt: input.prompt,
        aspectRatio: veoAspect,
        quality: input.quality,
        durationSeconds: input.durationSeconds,
        referenceImageBase64: input.referenceImageBase64,
        referenceImageMime: input.referenceImageMime,
        // Veo: seed/resolution/endImage silently ignored (capabilities flag declares them off).
      });
      return veoResultToMulti(r);
    } catch (err) {
      throw new MultiVideoGenError(
        err instanceof Error ? err.message : 'Veo 3.1 generation failed',
        'veo-3-img2vid',
        err,
      );
    }
  },
};

// ── Seedance 2.0 (fal.ai) wrapper ────────────────────────────────────────────

const SEEDANCE_CAPABILITIES: MultiVideoGenCapabilities = {
  supports_aspects: ['16:9', '9:16', '1:1', '21:9', '4:3', '3:4', 'auto'],
  supports_qualities: ['fast', 'standard'],
  supports_reference_image: true,
  requires_reference_image: true,
  // Sprint β 2026-05-14: full native range exposed (was capped at 8s for Phase 2
  // animatic parity). UI control panel now lets Director pick anywhere in [4,15].
  min_duration_s: 4,
  max_duration_s: 15,
  supports_resolutions: ['480p', '720p', '1080p'],
  supports_seed: true,
  supports_end_image: true,
  max_prompt_chars: 3000,
};

function seedanceResultToMulti(r: FalSeedanceResult): MultiVideoGenResult {
  return {
    status: 'success',
    provider: r.provider,
    format: r.format,
    width: r.width,
    height: r.height,
    duration_seconds: r.duration_seconds,
    size_bytes: r.size_bytes,
    mp4_b64: r.mp4_b64,
    cost_usd: r.cost_usd,
    model_id: r.model_id,
    operation_name: r.operation_name,
  };
}

export const seedanceFalProvider: MultiVideoGenProvider = {
  id: 'seedance-fal-img2vid',
  capabilities: SEEDANCE_CAPABILITIES,
  async generate(input: MultiVideoGenInput): Promise<MultiVideoGenResult> {
    try {
      const r = await generateVideoFalSeedance({
        prompt: input.prompt,
        aspectRatio: input.aspectRatio,
        quality: input.quality,
        durationSeconds: input.durationSeconds,
        referenceImageBase64: input.referenceImageBase64,
        referenceImageMime: input.referenceImageMime,
        resolution: input.resolution,
        seed: input.seed,
        endImageBase64: input.endImageBase64,
        endImageMime: input.endImageMime,
      });
      return seedanceResultToMulti(r);
    } catch (err) {
      throw new MultiVideoGenError(
        err instanceof Error ? err.message : 'Seedance 2.0 generation failed',
        'seedance-fal-img2vid',
        err,
      );
    }
  },
};

// ── Wan 2.6 Flash (fal.ai) wrapper ───────────────────────────────────────────

const WAN_FLASH_CAPABILITIES: MultiVideoGenCapabilities = {
  supports_aspects: ['16:9', '9:16', '1:1', '4:3', '3:4'],
  supports_qualities: ['fast'],
  supports_reference_image: true,
  requires_reference_image: true,
  min_duration_s: 5,
  max_duration_s: 15,
  supports_resolutions: ['720p'],
  supports_seed: false,
  supports_end_image: false,
  max_prompt_chars: 2000,
};

function wan26ResultToMulti(r: FalWanResult): MultiVideoGenResult {
  return {
    status: 'success',
    provider: r.provider,
    format: r.format,
    width: r.width,
    height: r.height,
    duration_seconds: r.duration_seconds,
    size_bytes: r.size_bytes,
    mp4_b64: r.mp4_b64,
    cost_usd: r.cost_usd,
    model_id: r.model_id,
    operation_name: r.operation_name,
  };
}

export const wan26FlashProvider: MultiVideoGenProvider = {
  id: 'wan-26-flash',
  capabilities: WAN_FLASH_CAPABILITIES,
  async generate(input: MultiVideoGenInput): Promise<MultiVideoGenResult> {
    const aspect = (input.aspectRatio === '21:9' || input.aspectRatio === 'auto')
      ? '16:9'
      : input.aspectRatio;
    const duration = (input.durationSeconds === 4 ? 5
      : input.durationSeconds === 6 || input.durationSeconds === 7 ? 5
      : input.durationSeconds === 8 ? 10
      : input.durationSeconds != null && input.durationSeconds > 10 ? 15
      : input.durationSeconds) as 5 | 10 | 15 | undefined;
    try {
      const r = await generateVideoFalWan({
        prompt: input.prompt,
        aspectRatio: aspect as import('./fal-wan').WanAspectRatio | undefined,
        durationSeconds: duration,
        referenceImageBase64: input.referenceImageBase64,
        referenceImageMime: input.referenceImageMime,
      });
      return wan26ResultToMulti(r);
    } catch (err) {
      throw new MultiVideoGenError(
        err instanceof Error ? err.message : 'Wan 2.6 Flash generation failed',
        'wan-26-flash',
        err,
      );
    }
  },
};

/** Lookup a provider by id. Future providers (Kling, Hailuo, Sora) plug in by
 *  exporting a `MultiVideoGenProvider` and adding a branch here. */
export function getMultiVideoProvider(id: string): MultiVideoGenProvider {
  if (id === 'veo-3-img2vid' || id === 'veo-3') return veo3Provider;
  if (id === 'seedance-fal-img2vid' || id === 'seedance-fal') return seedanceFalProvider;
  if (id === 'wan-26-flash') return wan26FlashProvider;
  throw new MultiVideoGenError(
    `Unknown video provider id "${id}" — supported: veo-3-img2vid, seedance-fal-img2vid, wan-26-flash`,
    id,
  );
}

/** Known provider ids that the router dispatches. Order is UI-display order. */
export const KNOWN_VIDEO_PROVIDER_IDS: ReadonlyArray<string> = [
  'seedance-fal-img2vid',
  'veo-3-img2vid',
  'wan-26-flash',
];
