// ──────────────────────────────────────────────────────────────────────────────
// lib/agents/providers/video-gen-multi.ts
// Provider-agnostic abstraction for video generation (Universal Video Editor
// Surface, Phase 1 of purrfect-stirring-hollerith plan).
//
// Why an abstraction layer:
//   - VGEN is the final visible output. Director must be able to switch
//     providers per shot (Veo 3 today, Kling/Sora/fal.ai tomorrow) without UI
//     or runner rewrites.
//   - Providers expose different per-stage controls. Universal Core knobs
//     (aspect/quality/duration/prompt/reference) live on this interface;
//     provider-specific knobs ride on the manifest in Phase 2.
//
// Phase 1 ships ONE concrete provider (Veo 3 via Gemini, generated by
// `veo-gemini.ts`). The wrapper below normalises the call surface so the
// runner doesn't import veo-gemini directly when extra providers land.
// ──────────────────────────────────────────────────────────────────────────────

import {
  generateVideoVeoGemini,
  type VeoAspectRatio,
  type VeoQualityTier,
  type VeoGeminiResult,
} from './veo-gemini';

// ── Universal Core types ─────────────────────────────────────────────────────

export type MultiVideoAspectRatio = VeoAspectRatio;
export type MultiVideoQualityTier = VeoQualityTier;

export interface MultiVideoGenInput {
  /** Composed prompt (already merged with shot details + episode title). */
  prompt: string;
  /** Universal Core: 16:9 (YouTube), 9:16 (Reels/Shorts), 1:1 (square). */
  aspectRatio?: MultiVideoAspectRatio;
  /** Universal Core: 'fast' (cheap) vs 'standard' (higher quality). */
  quality?: MultiVideoQualityTier;
  /** Universal Core: 1-8 second clips. */
  durationSeconds?: number;
  /** Universal Core: optional img2vid reference frame. */
  referenceImageBase64?: string;
  referenceImageMime?: 'image/png' | 'image/jpeg';
}

export interface MultiVideoGenResult {
  status: 'success';
  /** Stable provider id. e.g. 'veo-3-img2vid' or 'veo-3'. */
  provider: string;
  format: 'MP4';
  width: number;
  height: number;
  duration_seconds: number;
  size_bytes: number;
  /** Base64-encoded MP4 bytes. */
  mp4_b64: string;
  cost_usd: number;
  /**
   * Underlying model id (e.g. `veo-3.1-fast-generate-preview`). Optional
   * because non-Veo providers (Kling/Sora) may use different ids; runner
   * persists when present.
   */
  model_id?: string;
  /** Provider-side operation/job id for cross-reference in vendor logs. */
  operation_name?: string;
}

export interface MultiVideoGenCapabilities {
  supports_aspects: ReadonlyArray<MultiVideoAspectRatio>;
  supports_qualities: ReadonlyArray<MultiVideoQualityTier>;
  supports_reference_image: boolean;
  /** Min/max clip duration in seconds. */
  min_duration_s: number;
  max_duration_s: number;
}

export interface MultiVideoGenProvider {
  /** Stable id used in `app_config` and asset metadata. */
  id: string;
  capabilities: MultiVideoGenCapabilities;
  generate(input: MultiVideoGenInput): Promise<MultiVideoGenResult>;
}

export class MultiVideoGenError extends Error {
  constructor(
    message: string,
    public readonly providerId: string,
    public readonly cause?: unknown,
  ) {
    super(message);
    this.name = 'MultiVideoGenError';
  }
}

// ── Veo 3 wrapper ────────────────────────────────────────────────────────────

const VEO_CAPABILITIES: MultiVideoGenCapabilities = {
  supports_aspects: ['16:9', '9:16', '1:1'],
  supports_qualities: ['fast', 'standard'],
  supports_reference_image: true,
  min_duration_s: 4,
  max_duration_s: 8,
};

function veoResultToMulti(r: VeoGeminiResult): MultiVideoGenResult {
  return {
    status: 'success',
    provider: r.provider,
    format: r.format,
    width: r.width,
    height: r.height,
    duration_seconds: r.duration_seconds,
    size_bytes: r.size_bytes,
    mp4_b64: r.mp4_b64,
    cost_usd: r.cost_usd,
    model_id: r.model_id,
    operation_name: r.operation_name,
  };
}

export const veo3Provider: MultiVideoGenProvider = {
  id: 'veo-3-img2vid',
  capabilities: VEO_CAPABILITIES,
  async generate(input: MultiVideoGenInput): Promise<MultiVideoGenResult> {
    try {
      const r = await generateVideoVeoGemini({
        prompt: input.prompt,
        aspectRatio: input.aspectRatio,
        quality: input.quality,
        durationSeconds: input.durationSeconds,
        referenceImageBase64: input.referenceImageBase64,
        referenceImageMime: input.referenceImageMime,
      });
      return veoResultToMulti(r);
    } catch (err) {
      throw new MultiVideoGenError(
        err instanceof Error ? err.message : 'Veo 3 generation failed',
        'veo-3-img2vid',
        err,
      );
    }
  },
};

/** Lookup a provider by id. Phase 1 only knows Veo 3; Phase 2+ adds Kling/etc. */
export function getMultiVideoProvider(id: string): MultiVideoGenProvider {
  if (id === 'veo-3-img2vid' || id === 'veo-3') return veo3Provider;
  throw new MultiVideoGenError(
    `Unknown video provider id "${id}" — Phase 1 supports only veo-3-img2vid`,
    id,
  );
}
